// firebase-config.js - Firebase Configuration
// This file is auto-generated from environment variables
// DO NOT edit this file directly - update your .env file or Vercel environment variables instead
// Firebase API keys are safe to expose in client-side code
// Security is handled via Firebase Authentication and Firestore Security Rules

const ENV = {
  firebase: {
    apiKey: "AIzaSyA4H_yOF-LVPVrAYxHcFSYTvICWjRc1dp8",
    authDomain: "blackpinksrilanka-df057.firebaseapp.com",
    projectId: "blackpinksrilanka-df057",
    storageBucket: "blackpinksrilanka-df057.firebasestorage.app",
    messagingSenderId: "199272956119",
    appId: "1:199272956119:web:49261c0fa81b67b4fbb092",
    measurementId: "G-WS37NM3BCX",
  },
};
