// firebase-config.js - Firebase Configuration
// This file is auto-generated from environment variables during build
// DO NOT edit this file directly - update your .env file or Vercel environment variables instead
// 
// Setup Instructions:
// 1. Copy .env.example to .env and fill in your Firebase credentials
// 2. Run `npm run build` to generate this file
// 3. For Vercel deployment, set environment variables in your Vercel dashboard
//
// Firebase API keys are safe to expose in client-side code
// Security is handled via Firebase Authentication and Realtime Database Security Rules

const ENV = {
  firebase: {
    apiKey: "YOUR_FIREBASE_API_KEY",
    authDomain: "YOUR_PROJECT_ID.firebaseapp.com",
    databaseURL: "https://YOUR_PROJECT_ID-default-rtdb.firebaseio.com",
    projectId: "YOUR_PROJECT_ID",
    storageBucket: "YOUR_PROJECT_ID.firebasestorage.app",
    messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
    appId: "YOUR_APP_ID",
    measurementId: "YOUR_MEASUREMENT_ID",
  },
};
