/**
 * Generate Firebase configuration from environment variables
 * This script reads from .env and generates js/firebase-config.js
 * 
 * For Vercel deployment: Set these as Environment Variables in your Vercel dashboard
 * For local development: Create a .env file in the project root
 */

const fs = require('fs');
const path = require('path');

// Load .env file if it exists (for local development)
function loadEnvFile() {
  const envPath = path.join(__dirname, '..', '.env');
  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    const lines = envContent.split('\n');
    
    lines.forEach(line => {
      const trimmedLine = line.trim();
      // Skip comments and empty lines
      if (!trimmedLine || trimmedLine.startsWith('#')) return;
      
      const [key, ...valueParts] = trimmedLine.split('=');
      if (key && valueParts.length > 0) {
        const value = valueParts.join('=').trim();
        process.env[key.trim()] = value;
      }
    });
  }
}

// Load environment variables
loadEnvFile();

// Firebase configuration from environment variables
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
  measurementId: process.env.FIREBASE_MEASUREMENT_ID
};

// Validate that all required values are present
const requiredKeys = ['apiKey', 'authDomain', 'projectId', 'storageBucket', 'messagingSenderId', 'appId'];
const missingKeys = requiredKeys.filter(key => !firebaseConfig[key]);

if (missingKeys.length > 0) {
  console.error('Error: Missing required Firebase configuration values:');
  missingKeys.forEach(key => console.error(`  - ${key}`));
  console.error('\nPlease set the corresponding environment variables or create a .env file.');
  process.exit(1);
}

// Generate the firebase-config.js content
const configContent = `// firebase-config.js - Firebase Configuration
// This file is auto-generated from environment variables
// DO NOT edit this file directly - update your .env file or Vercel environment variables instead
// Firebase API keys are safe to expose in client-side code
// Security is handled via Firebase Authentication and Firestore Security Rules

const ENV = {
  firebase: {
    apiKey: "${firebaseConfig.apiKey}",
    authDomain: "${firebaseConfig.authDomain}",
    projectId: "${firebaseConfig.projectId}",
    storageBucket: "${firebaseConfig.storageBucket}",
    messagingSenderId: "${firebaseConfig.messagingSenderId}",
    appId: "${firebaseConfig.appId}",
    measurementId: "${firebaseConfig.measurementId || ''}",
  },
};
`;

// Write the configuration file
const outputPath = path.join(__dirname, '..', 'js', 'firebase-config.js');
fs.writeFileSync(outputPath, configContent);

console.log('✓ Firebase configuration generated successfully!');
console.log(`  Output: js/firebase-config.js`);
console.log(`  Project ID: ${firebaseConfig.projectId}`);
